RIGHT_SHARPA_KUKA_LINK_TO_ADJACENT_LINKS = {
    "iiwa14_link_0": ["iiwa14_link_1"],
    "iiwa14_link_1": ["iiwa14_link_0", "iiwa14_link_2"],
    "iiwa14_link_2": ["iiwa14_link_1", "iiwa14_link_3"],
    "iiwa14_link_3": ["iiwa14_link_2", "iiwa14_link_4"],
    "iiwa14_link_4": ["iiwa14_link_3", "iiwa14_link_5"],
    "iiwa14_link_5": ["iiwa14_link_4", "iiwa14_link_6"],
    "iiwa14_link_6": ["iiwa14_link_5", "iiwa14_link_7"],
    "iiwa14_link_7": [
        "iiwa14_link_6",
        "right_index_MCP_VL",
        "right_middle_MCP_VL",
        "right_pinky_MC",
        "right_ring_MCP_VL",
        "right_thumb_CMC_VL",
    ],
    "right_index_MCP_VL": ["iiwa14_link_7", "right_index_PP"],
    "right_index_PP": ["right_index_MCP_VL", "right_index_MP"],
    "right_index_MP": ["right_index_PP", "right_index_DP"],
    "right_index_DP": ["right_index_MP"],
    "right_middle_MCP_VL": ["iiwa14_link_7", "right_middle_PP"],
    "right_middle_PP": ["right_middle_MCP_VL", "right_middle_MP"],
    "right_middle_MP": ["right_middle_PP", "right_middle_DP"],
    "right_middle_DP": ["right_middle_MP"],
    "right_pinky_MC": ["iiwa14_link_7", "right_pinky_MCP_VL"],
    "right_pinky_MCP_VL": ["right_pinky_MC", "right_pinky_PP"],
    "right_pinky_PP": ["right_pinky_MCP_VL", "right_pinky_MP"],
    "right_pinky_MP": ["right_pinky_PP", "right_pinky_DP"],
    "right_pinky_DP": ["right_pinky_MP"],
    "right_ring_MCP_VL": ["iiwa14_link_7", "right_ring_PP"],
    "right_ring_PP": ["right_ring_MCP_VL", "right_ring_MP"],
    "right_ring_MP": ["right_ring_PP", "right_ring_DP"],
    "right_ring_DP": ["right_ring_MP"],
    "right_thumb_CMC_VL": ["iiwa14_link_7", "right_thumb_MC"],
    "right_thumb_MC": ["right_thumb_CMC_VL", "right_thumb_MCP_VL"],
    "right_thumb_MCP_VL": ["right_thumb_MC", "right_thumb_PP"],
    "right_thumb_PP": ["right_thumb_MCP_VL", "right_thumb_DP"],
    "right_thumb_DP": ["right_thumb_PP"],
}

LEFT_SHARPA_KUKA_LINK_TO_ADJACENT_LINKS = {
    "iiwa14_link_0": ["iiwa14_link_1"],
    "iiwa14_link_1": ["iiwa14_link_0", "iiwa14_link_2"],
    "iiwa14_link_2": ["iiwa14_link_1", "iiwa14_link_3"],
    "iiwa14_link_3": ["iiwa14_link_2", "iiwa14_link_4"],
    "iiwa14_link_4": ["iiwa14_link_3", "iiwa14_link_5"],
    "iiwa14_link_5": ["iiwa14_link_4", "iiwa14_link_6"],
    "iiwa14_link_6": ["iiwa14_link_5", "iiwa14_link_7"],
    "iiwa14_link_7": [
        "iiwa14_link_6",
        "left_thumb_CMC_VL",
        "left_thumb_MC",
        "left_index_MCP_VL",
        "left_index_PP",
        "left_middle_MCP_VL",
        "left_middle_PP",
        "left_ring_MCP_VL",
        "left_ring_PP",
        "left_pinky_MC",
    ],
    "left_index_MCP_VL": ["iiwa14_link_7", "left_index_PP"],
    "left_index_PP": ["iiwa14_link_7", "left_index_MCP_VL", "left_index_MP"],
    "left_index_MP": ["left_index_PP", "left_index_DP"],
    "left_index_DP": ["left_index_MP"],
    "left_middle_MCP_VL": ["iiwa14_link_7", "left_middle_PP"],
    "left_middle_PP": ["iiwa14_link_7", "left_middle_MCP_VL", "left_middle_MP"],
    "left_middle_MP": ["left_middle_PP", "left_middle_DP"],
    "left_middle_DP": ["left_middle_MP"],
    "left_pinky_MC": ["iiwa14_link_7", "left_pinky_MCP_VL", "left_pinky_PP"],
    "left_pinky_MCP_VL": ["left_pinky_MC", "left_pinky_PP"],
    "left_pinky_PP": ["left_pinky_MC", "left_pinky_MCP_VL", "left_pinky_MP"],
    "left_pinky_MP": ["left_pinky_PP", "left_pinky_DP"],
    "left_pinky_DP": ["left_pinky_MP"],
    "left_ring_MCP_VL": ["iiwa14_link_7", "left_ring_PP"],
    "left_ring_PP": ["iiwa14_link_7", "left_ring_MCP_VL", "left_ring_MP"],
    "left_ring_MP": ["left_ring_PP", "left_ring_DP"],
    "left_ring_DP": ["left_ring_MP"],
    "left_thumb_CMC_VL": ["iiwa14_link_7", "left_thumb_MC"],
    "left_thumb_MC": [
        "iiwa14_link_7",
        "left_thumb_CMC_VL",
        "left_thumb_MCP_VL",
        "left_thumb_PP",
    ],
    "left_thumb_MCP_VL": ["left_thumb_MC", "left_thumb_PP"],
    "left_thumb_PP": ["left_thumb_MC", "left_thumb_MCP_VL", "left_thumb_DP"],
    "left_thumb_DP": ["left_thumb_PP"],
}


RIGHT_LINKERHAND_UNITREE_LINK_TO_ADJACENT_LINKS = {
    "pelvis": ["right_shoulder_pitch_link"],
    "right_shoulder_pitch_link": ["right_shoulder_roll_link", "pelvis"],
    "right_shoulder_roll_link": ["right_shoulder_pitch_link", "right_shoulder_yaw_link"],
    "right_shoulder_yaw_link": ["right_elbow_link", "right_shoulder_roll_link"],
    "right_elbow_link": ["right_shoulder_yaw_link", "right_wrist_roll_link"],
    "right_wrist_roll_link": ["right_elbow_link", "right_wrist_pitch_link"],
    "right_wrist_pitch_link": ["right_wrist_roll_link", "right_wrist_yaw_link"],
    "right_wrist_yaw_link": [
        "right_wrist_pitch_link", 
        "rh_thumb_metacarpals_base2",
        "rh_thumb_metacarpals",
        "rh_thumb_distal",
        "rh_index_proximal",
        "rh_index_distal",
        "rh_middle_proximal",
        "rh_middle_distal",
        "rh_pinky_proximal",
        "rh_pinky_distal",
        "rh_ring_proximal",
        "rh_ring_distal",
    ],
    "rh_thumb_metacarpals_base2": ["right_wrist_yaw_link", "rh_thumb_metacarpals"],
    "rh_thumb_metacarpals": ["rh_thumb_distal", "rh_thumb_metacarpals_base2"],
    "rh_thumb_distal": ["rh_thumb_metacarpals"],
    "rh_index_proximal": ["right_wrist_yaw_link", "rh_index_distal"],
    "rh_index_distal": ["rh_index_proximal"],
    "rh_middle_proximal": ["right_wrist_yaw_link", "rh_middle_distal"],
    "rh_middle_distal": ["rh_middle_proximal"],
    "rh_ring_proximal": ["right_wrist_yaw_link", "rh_ring_distal"],
    "rh_ring_distal": ["rh_ring_proximal"],
    "rh_pinky_proximal": ["right_wrist_yaw_link", "rh_pinky_distal"],
    "rh_pinky_distal": ["rh_pinky_proximal"],
}

LEFT_LINKERHAND_UNITREE_LINK_TO_ADJACENT_LINKS = {
    "pelvis": ["left_shoulder_pitch_link"],
    "left_shoulder_pitch_link": ["left_shoulder_roll_link", "pelvis"],
    "left_shoulder_roll_link": ["left_shoulder_pitch_link", "left_shoulder_yaw_link"],
    "left_shoulder_yaw_link": ["left_elbow_link", "left_shoulder_roll_link"],
    "left_elbow_link": ["left_shoulder_yaw_link", "left_wrist_roll_link"],
    "left_wrist_roll_link": ["left_elbow_link", "left_wrist_pitch_link"],
    "left_wrist_pitch_link": ["left_wrist_roll_link", "left_wrist_yaw_link"],
    "left_wrist_yaw_link": [
        "left_wrist_pitch_link", 
        "lh_thumb_metacarpals_base2",
        "lh_thumb_metacarpals",
        "lh_thumb_distal",
        "lh_index_proximal",
        "lh_index_distal",
        "lh_middle_proximal",
        "lh_middle_distal",
        "lh_pinky_proximal",
        "lh_pinky_distal",
        "lh_ring_proximal",
        "lh_ring_distal",
    ],
    "lh_thumb_metacarpals_base2": ["left_wrist_yaw_link", "lh_thumb_metacarpals"],
    "lh_thumb_metacarpals": ["lh_thumb_distal", "lh_thumb_metacarpals_base2"],
    "lh_thumb_distal": ["lh_thumb_metacarpals"],
    "lh_index_proximal": ["left_wrist_yaw_link", "lh_index_distal"],
    "lh_index_distal": ["lh_index_proximal"],
    "lh_middle_proximal": ["left_wrist_yaw_link", "lh_middle_distal"],
    "lh_middle_distal": ["lh_middle_proximal"],
    "lh_ring_proximal": ["left_wrist_yaw_link", "lh_ring_distal"],
    "lh_ring_distal": ["lh_ring_proximal"],
    "lh_pinky_proximal": ["left_wrist_yaw_link", "lh_pinky_distal"],
    "lh_pinky_distal": ["lh_pinky_proximal"],
    
}