LEFT_LINKERHAND_G1_LINK_TO_ADJACENT_LINKS = {
    "pelvis": [
        "left_hip_pitch_link",
        "pelvis_contour_link",
        "right_hip_pitch_link",
        "waist_yaw_link",
    ],
    "pelvis_contour_link": ["pelvis"],
    "left_hip_pitch_link": ["left_hip_roll_link", "pelvis"],
    "left_hip_roll_link": ["left_hip_pitch_link", "left_hip_yaw_link"],
    "left_hip_yaw_link": ["left_hip_roll_link", "left_knee_link"],
    "left_knee_link": ["left_ankle_pitch_link", "left_hip_yaw_link"],
    "left_ankle_pitch_link": ["left_ankle_roll_link"],
    "left_ankle_roll_link": ["left_ankle_pitch_link"],
    "right_hip_pitch_link": ["pelvis", "right_hip_roll_link"],
    "right_hip_roll_link": ["right_hip_pitch_link", "right_hip_yaw_link"],
    "right_hip_yaw_link": ["right_hip_roll_link", "right_knee_link"],
    "right_knee_link": ["right_ankle_pitch_link", "right_hip_yaw_link"],
    "right_ankle_pitch_link": ["right_ankle_roll_link"],
    "right_ankle_roll_link": ["right_ankle_pitch_link"],
    "waist_yaw_link": ["pelvis", "waist_roll_link"],
    "waist_roll_link": ["torso_link", "waist_yaw_link"],
    "torso_link": [
        "d435_link",
        "head_link",
        "imu_in_torso",
        "left_shoulder_pitch_link",
        "logo_link",
        "mid360_link",
        "right_shoulder_pitch_link",
        "waist_roll_link",
        "waist_support_link",
    ],
    "logo_link": ["torso_link"],
    "head_link": ["torso_link"],
    "waist_support_link": ["torso_link"],
    "imu_in_torso": ["torso_link"],
    "imu_in_pelvis": ["pelvis"],
    "d435_link": ["torso_link"],
    "mid360_link": ["torso_link"],
    "left_shoulder_pitch_link": ["left_shoulder_roll_link", "torso_link"],
    "left_shoulder_roll_link": ["left_shoulder_pitch_link", "left_shoulder_yaw_link"],
    "left_shoulder_yaw_link": ["left_elbow_link", "left_shoulder_roll_link"],
    "left_elbow_link": ["left_shoulder_yaw_link", "left_wrist_roll_link"],
    "left_wrist_roll_link": ["left_elbow_link", "left_wrist_pitch_link"],
    "left_wrist_pitch_link": ["left_wrist_roll_link", "left_wrist_yaw_link"],
    "left_wrist_yaw_link": ["left_wrist_pitch_link", "lh_hand_base_link"],
    "right_shoulder_pitch_link": ["right_shoulder_roll_link", "torso_link"],
    "right_shoulder_roll_link": [
        "right_shoulder_pitch_link",
        "right_shoulder_yaw_link",
    ],
    "right_shoulder_yaw_link": ["right_elbow_link", "right_shoulder_roll_link"],
    "right_elbow_link": ["right_shoulder_yaw_link", "right_wrist_roll_link"],
    "right_wrist_roll_link": ["right_elbow_link", "right_wrist_pitch_link"],
    "right_wrist_pitch_link": ["right_wrist_roll_link", "right_wrist_yaw_link"],
    "right_wrist_yaw_link": ["rh_hand_base_link", "right_wrist_pitch_link"],
    "lh_hand_base_link": [
        "left_wrist_yaw_link",
        "lh_index_proximal",
        "lh_middle_proximal",
        "lh_pinky_proximal",
        "lh_ring_proximal",
        "lh_thumb_metacarpals_base2",
    ],
    "lh_thumb_metacarpals_base2": ["lh_hand_base_link", "lh_thumb_metacarpals"],
    "lh_thumb_metacarpals": ["lh_thumb_distal", "lh_thumb_metacarpals_base2"],
    "lh_thumb_distal": ["lh_thumb_metacarpals"],
    "lh_index_proximal": ["lh_hand_base_link", "lh_index_distal"],
    "lh_index_distal": ["lh_index_proximal"],
    "lh_middle_proximal": ["lh_hand_base_link", "lh_middle_distal"],
    "lh_middle_distal": ["lh_middle_proximal"],
    "lh_ring_proximal": ["lh_hand_base_link", "lh_ring_distal"],
    "lh_ring_distal": ["lh_ring_proximal"],
    "lh_pinky_proximal": ["lh_hand_base_link", "lh_pinky_distal"],
    "lh_pinky_distal": ["lh_pinky_proximal"],
    "rh_hand_base_link": [
        "rh_index_proximal",
        "rh_middle_proximal",
        "rh_pinky_proximal",
        "rh_ring_proximal",
        "rh_thumb_metacarpals_base2",
        "right_wrist_yaw_link",
    ],
    "rh_thumb_metacarpals_base2": ["rh_hand_base_link", "rh_thumb_metacarpals"],
    "rh_thumb_metacarpals": ["rh_thumb_distal", "rh_thumb_metacarpals_base2"],
    "rh_thumb_distal": ["rh_thumb_metacarpals"],
    "rh_index_proximal": ["rh_hand_base_link", "rh_index_distal"],
    "rh_index_distal": ["rh_index_proximal"],
    "rh_middle_proximal": ["rh_hand_base_link", "rh_middle_distal"],
    "rh_middle_distal": ["rh_middle_proximal"],
    "rh_ring_proximal": ["rh_hand_base_link", "rh_ring_distal"],
    "rh_ring_distal": ["rh_ring_proximal"],
    "rh_pinky_proximal": ["rh_hand_base_link", "rh_pinky_distal"],
    "rh_pinky_distal": ["rh_pinky_proximal"],
}
